language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly

before_install: 
    - sudo apt-get -qq update
    - sudo apt-get install -y cmake
    - sudo apt-get install -y libgtk-3-dev

script:
    - cd ui-sys
    - cargo build --verbose --tests --examples
    - cd ../ui
    - cargo build --verbose --tests --examples
